#!/bin/sh

# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b 3.3.10 $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Check flutter version
flutter --version

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --ios

# Install Flutter dependencies.
flutter pub get
flutter pub global activate intl_utils 2.8.1
flutter --no-color pub global run intl_utils:generate

exit 0