name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'
          channel: 'stable'
      - run: flutter --version
  check-all:
    needs: setup
    runs-on: macos-latest
    steps:
      - run: sudo ./scripts/check-all
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3