name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo ./scripts/setup-server
  check-all:
    needs: setup
    runs-on: macos-latest
    steps:
      - run: sudo ./scripts/check-all
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v